version: "3"

env:
  DB_PATH: "database.db"

tasks:
  setup:
    desc: Initial project setup
    cmds:
      - "docker compose build"

  upgrade:
    desc: Apply all migrations
    cmds:
      - "docker compose exec backend uv run alembic upgrade head"

  downgrade:
    desc: Revert last migration
    cmds:
      - "docker compose exec backend uv run alembic downgrade -1"

  migrate:
    desc: 'Create a new Alembic migration (to use: task migrate -- "message")'
    cmds:
      - "docker compose exec backend uv run alembic revision --autogenerate -m \"{{.CLI_ARGS}}\""

  dev:
    desc: Run FastAPI dev server
    cmds:
      - "docker compose up --build --watch"

  test:
    desc: Run tests with separate DB
    cmds:
      - "docker compose exec backend sh -c 'DB_PATH=test.db uv run pytest -vvs'"
