"""'Add nullable idx columns'

Revision ID: 9d85d356a614
Revises: 73d2e0f178ae
Create Date: 2025-11-19 17:50:11.235971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d85d356a614'
down_revision: Union[str, Sequence[str], None] = '73d2e0f178ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csvmetadata', sa.Column('idx_id', sa.Integer(), nullable=True))
    op.add_column('csvmetadata', sa.Column('idx_date', sa.Integer(), nullable=True))
    op.add_column('csvmetadata', sa.Column('idx_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csvmetadata', 'idx_value')
    op.drop_column('csvmetadata', 'idx_date')
    op.drop_column('csvmetadata', 'idx_id')
    # ### end Alembic commands ###
