"""'Add idx_id, idx_date, idx_value columns'

Revision ID: 536effe187e8
Revises: 73d2e0f178ae
Create Date: 2025-11-14 02:24:55.337357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536effe187e8'
down_revision: Union[str, Sequence[str], None] = '73d2e0f178ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csvmetadata', sa.Column('idx_id', sa.Integer(), nullable=True))
    op.add_column('csvmetadata', sa.Column('idx_date', sa.Integer(), nullable=True))
    op.add_column('csvmetadata', sa.Column('idx_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csvmetadata', 'idx_value')
    op.drop_column('csvmetadata', 'idx_date')
    op.drop_column('csvmetadata', 'idx_id')
    # ### end Alembic commands ###
