"""'Make idx_* values non-nullable'

Revision ID: 62c04edb1400
Revises: 536effe187e8
Create Date: 2025-11-19 15:18:39.296353

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62c04edb1400"
down_revision: Union[str, Sequence[str], None] = "536effe187e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("csvmetadata", "idx_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "csvmetadata", "idx_date", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "csvmetadata", "idx_value", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "csvmetadata", "idx_value", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "csvmetadata", "idx_date", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("csvmetadata", "idx_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
